version: 1.0.{build}
image: Visual Studio 2022
configuration: Debug
environment:
  COVERALLS_REPO_TOKEN:
    secure: pji/PrfzeqSnJ+t5Ltr9Evk/1ia+/Tzjic6Z49/BSGaq7duXx0V5Y9mxVxzplfwr
install:
  - cmd: dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
before_build:
  - cmd: >-
      dotnet --version
      
      dotnet --list-sdks
      
      dotnet restore
build:
  verbosity: minimal
after_build:
  - sh: ./tools/csmacnz.Coveralls --opencover -i ./vCardLib.Tests/coverage.opencover.xml --repoToken $COVERALLS_REPO_TOKEN
test_script:
  - cmd: dotnet test
deploy: off