version: '{build}'

branches:
  except:
    - gh-pages

image: Visual Studio 2022

clone_folder: c:\projects\

environment:
  COVERALLS_REPO_TOKEN:
    secure: obfhFAhjtB1sLMHFcfixbb75zgIFFUf7X2hsNHyi62eYBUQkd8AwpzbjQ8vFdc5l
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

platform: Any CPU

configuration: Debug

before_build:
  - cmd: dotnet restore

test_script:
  - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
