version: '1.{build}'
image: Ubuntu2004
clone_folder: c:\projects\
branches:
  except:
    - gh-pages
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
test_script:
  - cmd: dotnet tool install coveralls.net --version 3.0.0 --tool-path tools
  - cmd: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - cmd: .\tools\csmacnz.Coveralls --opencover -i ".\vCardLib.Tests\coverage.opencover.xml" --repoToken obfhFAhjtB1sLMHFcfixbb75zgIFFUf7X2hsNHyi62eYBUQkd8AwpzbjQ8vFdc5l
