version: '{build}'

branches:
  except:
    - gh-pages

image: Visual Studio 2017

clone_folder: c:\projects\

environment:
  COVERALLS_REPO_TOKEN:
    secure: 5xIkb6RiiVnvka4l9AKKGHwKl86XcJcyE
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

platform: Any CPU

configuration: Debug

build:
  parallel: true
  project: vCardLib.sln
  verbosity: minimal

before_build:
  - cmd: dotnet restore

test_script:
  - ps: .\coverage.ps1 
